language: erlang
otp_release:
  - 22.0
  - 21.3
script:
  - travis_wait rebar3 do compile, ct, proper --cover, dialyzer, xref, cover, coveralls send
cache:
  directories:
     - "$HOME/.cache/rebar3"
