name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [21.3]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run CT Tests
      run: rebar3 ct --suite els_parser_SUITE
    - name: Create Cover Reports
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: rebar3 do cover, coveralls send
